### ISSUE TITLE
feathers-client in peerDependencies ?

### ISSUE THREAD

**Issue by fonzarely** [josx/aor-feathers-client#15]
feathers-client package may be in peerDependencies aside admin-on-rest on package.json 

I'm not sure, what do you think of that ?

**Comment by wedneyyuri** [comment]
Hi @fonzarely, are you talking about 6bedf17e74b305328472e7a7b46c6ed83739147f?

**Comment by fonzarely** [comment]
Yes, you should add 'feathers-client' so that npm/yarn hit a warning when installing 'aor-feathers-client'.

**Comment by josx** [comment]
i think you are right.

**Comment by josx** [comment]
hey @wedneyyuri or @fonzarely Do you want to do a PR on that?
I am using aor-feathers-client with feathers-client 1.9.x, but some months ago they released 2.x
Can you check if it works with 2.x?

**Comment by fonzarely** [comment]
It does not seems to work with feathers-client 2.x since I'm bumping on a bug with my api 'id/_id'. I do not see a way to make admin-on-rest to manages the mapping. It might be a know bug, I'm not sure.

**Comment by wedneyyuri** [comment]
Hi @fonzarely, I'm using `aor-feathers-client@0.3.1`, `feathers-client@2.2.0` and `admin-on-rest@1.0.2` and everything is working fine.


> I'm bumping on a bug with my api 'id/_id'. I do not see a way to make admin-on-rest to manages the mapping. It might be a know bug, I'm not sure.

You can check https://github.com/josx/aor-feathers-client/issues/16 or https://github.com/josx/aor-feathers-client/issues/16#issuecomment-302902856

**Comment by fonzarely** [comment]
Thanks ! this is what I was looking for.

**Comment by josx** [comment]
So i merged @fonzarely PR https://github.com/josx/aor-feathers-client/pull/19 

But if @wedneyyuri is sure about it is working on 2.x we need to change peerdep to >1.9.x or something like that

**Comment by fonzarely** [comment]
No problem for me since I could fix the _id/id issue.
