### ISSUE TITLE
Custom identifiers/primary keys for in resources

### ISSUE THREAD

**Issue by wedneyyuri** [josx/aor-feathers-client#16]
Hi @josx, do you have any thoughts about custom identifiers? It is an issue when choosing NeDB as database.

The [proposed solution](https://marmelab.com/admin-on-rest/FAQ.html#can-i-have-custom-identifiersprimary-keys-for-my-resources) from FAQ:

>  If your REST API uses a different name for the primary key, you have to map that name to id in a custom restClient.

**Comment by josx** [comment]
What do you think about sending config when passing feathers client (with a default with id fields).

Using it:

```
<Admin
    restClient={restClient(feathersClient, { id: '_id' })}
  >
```
and in restClient.js

```
export default (client, options = { id: 'id' })  => {
... rewriting all calls to feathers client with proposed solution...
}
```

Do you want to work on this?

**Comment by wedneyyuri** [comment]
Your solution looks good to me. I wanna work on it, but probably I will not have time until the next weekend.

**Comment by wedneyyuri** [comment]
Until then, I'm using a server side hook:

in `src/services/customers/customers.hooks.js`:
```js
const normalizeId = require('../../hooks/normalize-id');

module.exports = {
  after: {
    all: [normalizeId()],
  },
};
```

in `src/hooks/normalize-id.js`:
```js
// Use this hook to manipulate incoming or outgoing data.
// For more information on hooks see: http://docs.feathersjs.com/api/hooks.html

module.exports = function (options = {}) { // eslint-disable-line no-unused-vars
  const normalizeID = (instance) => {
    instance.id = instance._id;
    delete instance._id;
    return instance;
  };

  return function (hook) {
    if (hook.method === 'find') {
      hook.result.data = hook.result.data.map(normalizeID);
    } else {
      hook.result = normalizeID(hook.result);
    }

    // Hooks can either return nothing or a promise
    // that resolves with the `hook` object for asynchronous operations
    return Promise.resolve(hook);
  };
};
```

**Comment by josx** [comment]
ok no problem we can wait to the next week ;)
