### ISSUE TITLE
Use PATCH instead of PUT

### ISSUE THREAD

**Issue by wedneyyuri** [josx/aor-feathers-client#20]
Discussion started in https://github.com/marmelab/admin-on-rest/issues/256

> We are sending all attributes as generally API doesn't handle PATCH but just PUT.
> https://github.com/marmelab/admin-on-rest/issues/256#issuecomment-274870099

And there are good news, because [feathers supports PATCH HTTP method](https://docs.feathersjs.com/api/rest.html#rest).

My proposal is [to change our mapRequest method](https://github.com/josx/aor-feathers-client/blob/4736b6d6411118b0aa18e9d2b71dee677084a2f9/src/restClient.js#L41) from `service.update(...)` to `service.patch(...)`:

**Comment by wedneyyuri** [comment]
Closing because I think it's a low priority improvement, sorry the noise

**Comment by josx** [comment]
maybe we can put both update and patch, if you need it or want PR is welcomed ;)
