### ISSUE TITLE
Add circleCI to automate PR testing ?

### ISSUE THREAD

**Issue by fonzarely** [josx/aor-feathers-client#22]
I'm using the free plan for my projects so I can propose this for this lib.

Would you like I make it ?

Exemple : 
![image](https://cloud.githubusercontent.com/assets/707217/26635199/4d50a84e-4619-11e7-949c-09d20554fdbb.png)

**Comment by josx** [comment]
Would be great to have a test advice. I didnt use circleCI before.
Please make a PR and comment on how to use it.

**Comment by fonzarely** [comment]
Done : 
https://github.com/josx/aor-feathers-client/pull/24
