### ISSUE TITLE
Deprecated package - react-addons-transition-group

### ISSUE THREAD

**Issue by fonzarely** [josx/aor-feathers-client#23]
warning admin-on-rest > material-ui > react-addons-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use TransitionGroup from 'react-transition-group' instead.

**Comment by josx** [comment]
is this still valid? how can i reprodce it?

**Comment by fonzarely** [comment]
This is a warning I had when building. I don't remember what can we do about it.
We may close this issue for now.

**Comment by josx** [comment]
ok if you reproduce it let me know.
