### ISSUE TITLE
Duplicated Presentation when using mongoose

### ISSUE THREAD

**Issue by 1beb** [josx/aor-feathers-client#25]
I have a feathers service that I can test with postman, and it shows a list of 4 records all distinct. However, when I try to use it with aor-feathers-client, no matter which model I use, the records are all being presented as equal. So let's say for example, we have a model for `reminders`. We would expect:

Reminders List

- reminder 1
- reminder 2
- ...

But what is appearing is:

Reminder List

- reminder 1
- reminder 1
- ...

![screenshot 2017-07-04 17 33 46](https://user-images.githubusercontent.com/421859/27843902-6a62a4e2-60df-11e7-8e56-fc36614e6821.png)

Where the first item is always duplicated. Also, when trying to edit, it simply passes 'undefined'. I'm not sure what I'm doing wrong here. I based it entirely off of your example: 

```
// App.js

import React from 'react';
import { Admin, Resource, simpleRestClient } from 'admin-on-rest';
import { RemindersList} from './Reminders';
import { restClient } from 'aor-feathers-client'; // authClient for future!
import feathersClient from './feathersClient';

const App = () => (
  <Admin restClient={restClient(feathersClient)}>
    <Resource name="reminders" list={ContactList} />
  </Admin>
);

export default App;

// Contact.js

import React from 'react';
import { Filter, DisabledInput, ReferenceInput, List, Edit, Create, SimpleForm, Datagrid, TextField, SelectInput, TextInput, EditButton } from 'admin-on-rest/lib/mui';

export const RemindersList = (props) => (
    <List {...props}>
        <Datagrid>
            <TextField source="_id" />
            <TextField source="credoId" />
            <TextField source="surveyId" />
            <TextField source="frequency" />
            <TextField source="nextReminder" />
            <EditButton />

        </Datagrid>
    </List>
);

// feathersClient.js

import feathers from 'feathers-client';
import hooks from 'feathers-hooks';
import rest from 'feathers-rest/client';

const host = 'http://localhost:3030';

export default feathers()
  .configure(hooks())
  .configure(rest(host).fetch(window.fetch.bind(window)));

```

**Comment by 1beb** [comment]
So, some more investigation shows that this is related to the use of feathers mongoose. I'm going to through together a reproducible example in a new repo. I think it has something to do with the field 'id'.

**Comment by 1beb** [comment]
```
{
    "name": "BadRequest",
    "message": "Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"reminders\"",
    "code": 400,
    "className": "bad-request",
    "errors": {}
}
```

This is a telling response from postman.

**Comment by 1beb** [comment]
This problem appears to be related to the ids, or more specifically the field name of the id (in this case _id).

**Comment by josx** [comment]
is there any errors on browser console or on feathers debug?

**Comment by josx** [comment]
check here:

https://github.com/feathersjs/feathers-mongoose/issues/81
https://github.com/feathersjs/feathers-mongoose/issues/156

@fonzarely Is working to support custom id (maybe you want to help)
https://github.com/josx/aor-feathers-client/pull/21

**Comment by thngdude** [comment]
I am experiencing this issue as well. Any workarounds?

**Comment by josx** [comment]
It seems to be that you are using mongo or somehting with custom id field name.
We are working to support that!
@thngdude if you can please help us! 
here WIP https://github.com/josx/aor-feathers-client/pull/21 (need tests, and @1beb told us that it is not working )
