### ISSUE TITLE
Authorization header missing from requests

### ISSUE THREAD

**Issue by lijoantony** [josx/aor-feathers-client#35]
I am facing an issue very similar to the one described here https://github.com/feathersjs/feathers-client/issues/68, but in the context of admin-on-rest. The first few service calls issued by the admin-on-rest doesn't have the Authorization header even though the token is available in the local storage. From the discussion in the linked issue, I understand that the service calls should be issued only after app.authenticate() call. However, I don't know where to insert the app.authenticate() call in the admin-on-rest control flow. Can any one tell me how to do this?

**Comment by josx** [comment]
Right now app.authenticate is called here https://github.com/josx/aor-feathers-client/blob/master/src/authClient.js#L20

**Comment by lijoantony** [comment]
This app.authenticate(...), with email and password, would be called when admin-on-request issues AUTH_LOGIN event. As per my understanding, AUTH_LOGIN would be issued when a LOGIN action is triggered from the Login component rendered at the login route. My scenario is different.

When the application is started, admin-on-rest would issue an AUTH_CHECK event upon entering a route. Now, depending on the availability of a token in the local storage, authClient would either resolve or reject the promise. Reject would result in a location change to login route and the normal login flow occurs.

But when the token is indeed available in the local storage, authClient would resolve the promise. Hence, admin-on-rest assumes, restClient will take care of adding Authorization header for the subsequent requests and will start issuing the rest commands to the restClient. However, this is not enough for the feathersClient to start inserting Authorization header into the requests. As described here (https://github.com/feathersjs/feathers-client/issues/68), we need to call app.authenticate() once, with empty params. Only after this call, feathersClient would recognize the token in the localStorage and start adding Authorization headers into the rest requests.

I have got it working by explicitly calling app.authenticate(), without any params, before admin-on-rest issues any rest calls. But I feel this is only a work around and there should be a better way to do this. I am wondering how others are doing this.

**Comment by josx** [comment]
@7flash @lijoantony  any idea on how to fix it? is there anyway to avoid this in aor-feathers-client?

**Comment by 7flash** [comment]
I created pull request that working for me

**Comment by josx** [comment]
I dont like the idea of calling app.authenticate on each request, but it solves that problem. 
So I merged the code.
