### ISSUE TITLE
GET_MANY does not return with id in mapResponse

### ISSUE THREAD

**Issue by dreamrace** [josx/aor-feathers-client#37]
Recording to aor [docs](https://marmelab.com/admin-on-rest/RestClients.html#response-format)
```
A {Record} is an object literal with at least an id property, e.g. { id: 123, title: "hello, world" }.
```

Currently there is no case to handle ```GET_MANY``` in mapResponse, which seems to break **\<ReferenceField\>** for my project.

A simple fix would be to add ```case GET_MANY: ``` to get same treatment as ```GET_LIST```?

```js
// src/restClient.js
const mapResponse = (response, type, resource, params) => {
    const idKey = getIdKey({resource, options})
    switch (type) {
      case GET_ONE:
      case UPDATE:
      case DELETE:
        return {data: {...response, id: response[idKey]}}
      case CREATE:
        return {data: {...params.data, id: response[idKey]}}
      case GET_MANY:  // added GET_MANY
      case GET_LIST:
        response.data = response.data.map(item => {
          if (idKey !== 'id') {
            item.id = item[idKey]
          }
          return item
        })
        return response
      default:
        return response
    }
}
```

**Comment by josx** [comment]
I think you are right on this, we forgot to include it.

Can you create a PR on this? I will be glad on merging it ;)

**Comment by dreamrace** [comment]
@josx I have spotted the same issue with GET_REFERENCE, I will submit PR with fix for both case.
Is that ok for you?

**Comment by josx** [comment]
ok! great merged ;)

**Comment by dreamrace** [comment]
Cheers!
