### ISSUE TITLE
feathers-jwt deleted on page reload

### ISSUE THREAD

**Issue by fonzarely** [josx/aor-feathers-client#39]
I'm using the authClient, the token is well saved in localstorage but is deleted on page reload.
Did someone had such issue previously ?

**Comment by josx** [comment]
maybe more info on  https://github.com/josx/aor-feathers-client/issues/35
@7flash any clue on this?

**Comment by 7flash** [comment]
Are you using last version from repository or from npm?

**Comment by fonzarely** [comment]
I'm using the last npm version : 
```` "dependencies": {
    "admin-on-rest": "^1.2.2",
    "aor-feathers-client": "^0.5.0",
    "aor-json-rest-client": "^2.0.0",
    "feathers-client": "^2.3.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-scripts": "1.0.11"
  }

**Comment by fonzarely** [comment]
I also tested with React 15.5

**Comment by josx** [comment]
Last github version is different from 0.5.0 on npm, i will released it right now

**Comment by josx** [comment]
Please check the new release 0.6.0, and please tell us @fonzarely  if it is working ok?

**Comment by fonzarely** [comment]
It works ! Thank you guys \O/
