### ISSUE TITLE
return object for restClient

### ISSUE THREAD

**Issue by sarkistlt** [josx/aor-feathers-client#40]
https://github.com/marmelab/admin-on-rest/pull/385

**Comment by sarkistlt** [comment]
otherwise I can see in debugger that I have response data in an array, but app shows error `Cannot read property 'map' of undefined`

**Comment by sarkistlt** [comment]
my bad, forgot to set pagination option in the service

**Comment by josx** [comment]
hey no problem, thanks for trying to contribute
If you test it and find something is not working as you want please add issue, and much better if you can do a PR ;)
