### ISSUE TITLE
Add AUTH_GET_PERMISSIONS to authClient

### ISSUE THREAD

**Issue by fonzarely** [josx/aor-feathers-client#43]
It would be nice to add AUTH_GET_PERMISSIONS, but I'm not sure if is relevant to add it to the this lib or decorate the authClient in my app.
What are your thoughts ?

**Comment by josx** [comment]
I think that would be great to support it on authClient. 

A few months ago marmelab released aor-permission:

https://github.com/marmelab/aor-permissions
https://marmelab.com/blog/2017/06/26/aor-permissions.html

**Comment by fonzarely** [comment]
Yes I saw that,
We have 2 options:
- pass the permissions aside the token,
- decode the jwt token to find permissions.

I think we should add the permission management via a function given as parameter to authClient.

I have a big need of this so I'll make it, let me know what you think of my proposition.

**Comment by josx** [comment]
Pass the permission aside the token, it is a more clean way to handle it, at least at first. 
(it is less work and then we can decide to upgrade it later)

**"scratch an itch"** is the perfect way to continue developing new features.

**Comment by fonzarely** [comment]
Added PR https://github.com/josx/aor-feathers-client/pull/45
