### ISSUE TITLE
Permission example in readme

### ISSUE THREAD

**Issue by kfern** [josx/aor-feathers-client#47]
Could you add a complete example about permissions?
Thanks in advance

**Comment by josx** [comment]
what do you want? backend?
I am not using permissions right now.
Also months ago there is a new plugin on Admin on rest to help with permissions (https://marmelab.com/blog/2017/06/26/aor-permissions.html)

Maybe @7flash or @fonzarely know more about this topic.

**Comment by kfern** [comment]
Anyone needs backend and frontend example because permissions are critical in admin apps.

A complete example will help to understand how use It.

**Comment by josx** [comment]
Some months ago i have started an example: https://github.com/Cambalab/test-feathers-admin/

But i didnt update it with the latest plugin version.

Maybe you can start there and try to update it, to get an running project with a complete backend and frontend example. 

@kfern PR are welcome ;)

**Comment by kfern** [comment]
I don't know enough admin-on-rest, but I could help with Integration tests (related to #4)

**Comment by kfern** [comment]
@josx https://github.com/marmelab/aor-permissions: This project is discontinued. Its features have been merged in admin-on-rest 1.3.0

**Comment by josx** [comment]
if you can help on integration tests would be great!

**Comment by kfern** [comment]
For the integration tests I will start a project from scratch. 

I'll need help with permissions setting, so a complete example will be perfect

**Comment by josx** [comment]
great! maybe then we can deploy it to heroku to get an online usable version.
No problem I can help you.

**Comment by kfern** [comment]
I have already started the project for integration tests. Repo url is [https://github.com/kfern/feathers-aor-test-integration](https://github.com/kfern/feathers-aor-test-integration)

In order to continue I need your help with an example on managing permissions. 

When can you have it?

**Comment by josx** [comment]
great!
@fonzarely and @7flash  can you also see  this?

**Comment by fonzarely** [comment]
Yes, I can. I have few availability now but will propose some thing.

**Comment by josx** [comment]
take a look on https://github.com/kfern/feathers-aor-test-integration and on PR https://github.com/kfern/feathers-aor-test-integration/pull/1

We are trying to make a usefull example of permission (enforcing on backend and frontened), it seems you know more than us in that topic. Your look would be helpfull, at leasy you can tell us how to do it.

**Comment by kfern** [comment]
Done :-)
https://github.com/kfern/feathers-aor-test-integration

**Comment by josx** [comment]
great work @kfern 
Can you add this to the README and make a PR?

**Comment by kfern** [comment]
Now I do not have much time but I will try to find it.

**Comment by kfern** [comment]
Done :-)
