### ISSUE TITLE
Rest client does not correctly handle GET_MANY

### ISSUE THREAD

**Issue by Ryanthegiantlion** [josx/aor-feathers-client#5]
See:

https://marmelab.com/admin-on-rest/RestClients.html#writing-your-own-rest-client

GET_MANY passes a list of ID's while GET_LIST passes a filter parameter. Currently the
GET_MANY handler for AOR Feathers Client is not handling a list of ID's as it is expecting a filter parameter.

**Comment by josx** [comment]
@Ryanthegiantlion we have to research how feathers client is handling many request? any clue on that?

**Comment by Ryanthegiantlion** [comment]
@josx As it stands the aor-feathers-client drops the id's for the GET_MANY request.

The above fix works for me. If you want to reproduce the error to test this fix use a reference field in a list view. AOR will fire off a GET_MANY for the associations with the id's of the reference fields. (As documented in the link above)
