### ISSUE TITLE
Does this work with feathers v3? [question]

### ISSUE THREAD

**Issue by AndrewJDR** [josx/aor-feathers-client#51]
Does this work with feathers v3? Thanks.

**Comment by josx** [comment]
I havent tested with feathers v3, but would be very usefull to support it.
It would be great if someone can test it and give us a feedback on that.

**Comment by ricardovf** [comment]
Here it worked.

``````
import feathers from '@feathersjs/client'

const app = feathers()

app.configure(feathers.rest('http://localhost:3030').fetch(window.fetch));

const authService = feathers.authentication({
  storage: window.localStorage,
})
app.configure(authService)

export default app
`````


```````
import { authClient, restClient } from 'aor-feathers-client'
import feathersClient from './rest/feathersClient'

const authClientOptions = {
  storageKey: 'feathers-jwt',
  authenticate: {strategy: 'local'},
}

const App = () => (
  <Admin
    authClient={authClient(feathersClient, authClientOptions)}
    restClient={restClient(feathersClient, options)}
  >

    <Resource name="users" icon={UsersIcon} list={UsersList}/>
  </Admin>
)
```````

**Comment by josx** [comment]
@ricardovf  great!
