### ISSUE TITLE
Filtering by nested properties

### ISSUE THREAD

**Issue by dprentis** [josx/aor-feathers-client#52]
Can't filter by nested properties, because query object is not flattened in restClient.js.

eg. when trying to filter `author.lastName='Brown'`, the query object becomes `{ author: { lastName: 'Brown' } }`, which results in an invalid query string. I think it should be `{ 'author.lastName': 'Brown' }`.

Easy fix seems to be to import fetchUtils
`import { fetchUtils } from 'admin-on-rest';`
and then replace
`Object.assign(query, params.filter);` here
https://github.com/josx/aor-feathers-client/blob/master/src/restClient.js#L50
with
`Object.assign(query, fetchUtils.flattenObject(params.filter));`

**Comment by josx** [comment]
hey! good catch!
Please make a PR for that feature and also for a test.

**Comment by dprentis** [comment]
Thanks for merging it! :) When are you planning the next release?

**Comment by josx** [comment]
I think will be in the following days ;)

**Comment by josx** [comment]
done!
