### ISSUE TITLE
Trouble accessing the "_id" value of the loggedin user

### ISSUE THREAD

**Issue by michaelgold** [josx/aor-feathers-client#54]
Hi -

Thanks for releasing this plugin! I am new to JWT and React, so please forgive me for the naive question. 

In AOR, is there a straightforward way to access the `_id` and `name` values of the logged in user?

I noticed that feathersClient saves the `roles` value of the logged in user to window.localStorage, and I'm not sure if that functionality would need to be replicated for the `_id` and `name` values of the logged in user or if there is an existing/better way to do it..

**Comment by josx** [comment]
Now you can check what is feathers-jwt with something like https://jwt.io/ 
An example of payload:

```
{
  "userId": "MY011cZCsBOrBdoa",
  "roles": "user",
  "iat": 1523883805,
  "exp": 1523970205,
  "aud": "https://yourdomain.com",
  "iss": "feathers",
  "sub": "anonymous"
}
```

I am thinking that you can get the User data directly from feathers user rest API.
