### ISSUE TITLE
Error for query filters

### ISSUE THREAD

**Issue by olegggI** [josx/aor-feathers-client#8]
Just change 

`query = { 'id': { '[$in]': ids } };`

to

`query = { 'id': { '$in': ids } };`

**Comment by josx** [comment]
With which feathers version you are testing it? auk or legacy?

**Comment by wedneyyuri** [comment]
Hi @josx, as [far I understand](https://github.com/feathersjs/feathers/issues/334) this code will not work with others db providers (ex: Sequelize or elasticsearch). 

Please, can you confirm the supported db?

**Comment by josx** [comment]
BTW We are using feathers client, with simple queries (So i think will work for all feathers supported dbs).

In feathers docs describe db adapter: [Pagination, Sorting, Limiting, and Selecting](https://legacy.docs.feathersjs.com/databases/pagination.html) and [querying](https://legacy.docs.feathersjs.com/databases/querying.html) 

Anyways would be great if you can test it on, so we can be sure to be db agnostic.

**Comment by AmrN** [comment]
Having the same issue, I'm using Auk but looking at the documentation for legacy it seems to be using the same syntax and neither of them requires these brackets:
[Auk's querying documentation](https://docs.feathersjs.com/api/databases/querying.html#in-nin)
[Legacy's querying documentation](https://legacy.docs.feathersjs.com/databases/querying.html#in-nin)

I sent a PR with the fix suggested by olegggI.

**Comment by josx** [comment]
Fixed with #12
